///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Winston_Agent_Portal
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ClassandPayroll recording.
    /// </summary>
    [TestModule("bdbc20ee-c165-46bd-852e-4229008de699", ModuleType.Recording, 1)]
    public partial class ClassandPayroll : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Winston_Agent_PortalRepository repository.
        /// </summary>
        public static Winston_Agent_PortalRepository repo = Winston_Agent_PortalRepository.Instance;

        static ClassandPayroll instance = new ClassandPayroll();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ClassandPayroll()
        {
            OtherPayAmnt = "";
            ActiveOwnerValue = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ClassandPayroll Instance
        {
            get { return instance; }
        }

#region Variables

        string _OtherPayAmnt;

        /// <summary>
        /// Gets or sets the value of variable OtherPayAmnt.
        /// </summary>
        [TestVariable("1187e6b3-ef14-4044-be0f-98ca67b9e879")]
        public string OtherPayAmnt
        {
            get { return _OtherPayAmnt; }
            set { _OtherPayAmnt = value; }
        }

        string _ActiveOwnerValue;

        /// <summary>
        /// Gets or sets the value of variable ActiveOwnerValue.
        /// </summary>
        [TestVariable("b34e62a1-8881-46a4-9d23-0ec0a6332726")]
        public string ActiveOwnerValue
        {
            get { return _ActiveOwnerValue; }
            set { _ActiveOwnerValue = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Select2DdlClassificationContainer' at Center.", repo.ApplicationUnderTest.Select2DdlClassificationContainerInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Select2DdlClassificationContainer.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '97220' with focus on 'ApplicationUnderTest'.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Self.EnsureVisible();
            Keyboard.Press("97220");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ApplicationUnderTest'.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Self.EnsureVisible();
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnAddClassification' at Center.", repo.ApplicationUnderTest.BtnAddClassificationInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.BtnAddClassification.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Percentage' at Center.", repo.ApplicationUnderTest.PercentageInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Percentage.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '100' with focus on 'ApplicationUnderTest.Percentage'.", repo.ApplicationUnderTest.PercentageInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Percentage.PressKeys("100");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.ExpectedGrossReceipts' at Center.", repo.ApplicationUnderTest.ExpectedGrossReceiptsInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.ExpectedGrossReceipts.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '250000' with focus on 'ApplicationUnderTest.ExpectedGrossReceipts'.", repo.ApplicationUnderTest.ExpectedGrossReceiptsInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.ExpectedGrossReceipts.PressKeys("250000");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.InsuredSubcontractorsCost' at Center.", repo.ApplicationUnderTest.InsuredSubcontractorsCostInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.InsuredSubcontractorsCost.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '35000' with focus on 'ApplicationUnderTest.InsuredSubcontractorsCost'.", repo.ApplicationUnderTest.InsuredSubcontractorsCostInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.InsuredSubcontractorsCost.PressKeys("35000");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ColLg12ColMd12ColSm12Pt2' at Center.", repo.ApplicationUnderTest.ColLg12ColMd12ColSm12Pt2Info, new RecordItemIndex(10));
            repo.ApplicationUnderTest.ColLg12ColMd12ColSm12Pt2.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.InsuredSubcontractorsOperations' at Center.", repo.ApplicationUnderTest.InsuredSubcontractorsOperationsInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.InsuredSubcontractorsOperations.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'OK' with focus on 'ApplicationUnderTest.InsuredSubcontractorsOperations'.", repo.ApplicationUnderTest.InsuredSubcontractorsOperationsInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.InsuredSubcontractorsOperations.PressKeys("OK");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Select2DdlClassCodesContainer' at Center.", repo.ApplicationUnderTest.Select2DdlClassCodesContainerInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.Select2DdlClassCodesContainer.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Search' at Center.", repo.ApplicationUnderTest.SearchInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.Search.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '91581' with focus on 'ApplicationUnderTest.Search'.", repo.ApplicationUnderTest.SearchInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.Search.PressKeys("91581");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ApplicationUnderTest.Search'.", repo.ApplicationUnderTest.SearchInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.Search.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnAddClassCode' at Center.", repo.ApplicationUnderTest.BtnAddClassCodeInfo, new RecordItemIndex(17));
            repo.ApplicationUnderTest.BtnAddClassCode.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Percentage1' at Center.", repo.ApplicationUnderTest.Percentage1Info, new RecordItemIndex(18));
            repo.ApplicationUnderTest.Percentage1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '100' with focus on 'ApplicationUnderTest.Percentage1'.", repo.ApplicationUnderTest.Percentage1Info, new RecordItemIndex(19));
            repo.ApplicationUnderTest.Percentage1.PressKeys("100");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.FullAdmEmp' at Center.", repo.ApplicationUnderTest.FullAdmEmpInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.FullAdmEmp.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '10' with focus on 'ApplicationUnderTest.FullAdmEmp'.", repo.ApplicationUnderTest.FullAdmEmpInfo, new RecordItemIndex(21));
            repo.ApplicationUnderTest.FullAdmEmp.PressKeys("10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.PartAdmEmp' at Center.", repo.ApplicationUnderTest.PartAdmEmpInfo, new RecordItemIndex(22));
            repo.ApplicationUnderTest.PartAdmEmp.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '5' with focus on 'ApplicationUnderTest.PartAdmEmp'.", repo.ApplicationUnderTest.PartAdmEmpInfo, new RecordItemIndex(23));
            repo.ApplicationUnderTest.PartAdmEmp.PressKeys("5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.TotAdmPayroll' at Center.", repo.ApplicationUnderTest.TotAdmPayrollInfo, new RecordItemIndex(24));
            repo.ApplicationUnderTest.TotAdmPayroll.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '25000' with focus on 'ApplicationUnderTest.TotAdmPayroll'.", repo.ApplicationUnderTest.TotAdmPayrollInfo, new RecordItemIndex(25));
            repo.ApplicationUnderTest.TotAdmPayroll.PressKeys("25000");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.FullSalesEmp' at Center.", repo.ApplicationUnderTest.FullSalesEmpInfo, new RecordItemIndex(26));
            repo.ApplicationUnderTest.FullSalesEmp.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '5' with focus on 'ApplicationUnderTest.FullSalesEmp'.", repo.ApplicationUnderTest.FullSalesEmpInfo, new RecordItemIndex(27));
            repo.ApplicationUnderTest.FullSalesEmp.PressKeys("5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.PartSalesEmp' at Center.", repo.ApplicationUnderTest.PartSalesEmpInfo, new RecordItemIndex(28));
            repo.ApplicationUnderTest.PartSalesEmp.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '2' with focus on 'ApplicationUnderTest.PartSalesEmp'.", repo.ApplicationUnderTest.PartSalesEmpInfo, new RecordItemIndex(29));
            repo.ApplicationUnderTest.PartSalesEmp.PressKeys("2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.TotSalesPayroll' at Center.", repo.ApplicationUnderTest.TotSalesPayrollInfo, new RecordItemIndex(30));
            repo.ApplicationUnderTest.TotSalesPayroll.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '10000' with focus on 'ApplicationUnderTest.TotSalesPayroll'.", repo.ApplicationUnderTest.TotSalesPayrollInfo, new RecordItemIndex(31));
            repo.ApplicationUnderTest.TotSalesPayroll.PressKeys("10000");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.FullPartners' at Center.", repo.ApplicationUnderTest.FullPartnersInfo, new RecordItemIndex(32));
            repo.ApplicationUnderTest.FullPartners.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.FullPartners'.", repo.ApplicationUnderTest.FullPartnersInfo, new RecordItemIndex(33));
            repo.ApplicationUnderTest.FullPartners.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.PartPartners' at Center.", repo.ApplicationUnderTest.PartPartnersInfo, new RecordItemIndex(34));
            repo.ApplicationUnderTest.PartPartners.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.PartPartners'.", repo.ApplicationUnderTest.PartPartnersInfo, new RecordItemIndex(35));
            repo.ApplicationUnderTest.PartPartners.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.FullOtherEmp' at Center.", repo.ApplicationUnderTest.FullOtherEmpInfo, new RecordItemIndex(36));
            repo.ApplicationUnderTest.FullOtherEmp.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '5' with focus on 'ApplicationUnderTest.FullOtherEmp'.", repo.ApplicationUnderTest.FullOtherEmpInfo, new RecordItemIndex(37));
            repo.ApplicationUnderTest.FullOtherEmp.PressKeys("5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.PartOtherEmp' at Center.", repo.ApplicationUnderTest.PartOtherEmpInfo, new RecordItemIndex(38));
            repo.ApplicationUnderTest.PartOtherEmp.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '2' with focus on 'ApplicationUnderTest.PartOtherEmp'.", repo.ApplicationUnderTest.PartOtherEmpInfo, new RecordItemIndex(39));
            repo.ApplicationUnderTest.PartOtherEmp.PressKeys("2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.TotOtherPayroll' at Center.", repo.ApplicationUnderTest.TotOtherPayrollInfo, new RecordItemIndex(40));
            repo.ApplicationUnderTest.TotOtherPayroll.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '75000' with focus on 'ApplicationUnderTest.TotOtherPayroll'.", repo.ApplicationUnderTest.TotOtherPayrollInfo, new RecordItemIndex(41));
            repo.ApplicationUnderTest.TotOtherPayroll.PressKeys("75000");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Value' from item 'ApplicationUnderTest.TotOtherPayroll' and assigning its value to variable 'OtherPayAmnt'.", repo.ApplicationUnderTest.TotOtherPayrollInfo, new RecordItemIndex(42));
            //OtherPayAmnt = repo.ApplicationUnderTest.TotOtherPayroll.Element.GetAttributeValueText("Value");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Value' from item 'ApplicationUnderTest.ActiveOwnerValue' and assigning its value to variable 'ActiveOwnerValue'.", repo.ApplicationUnderTest.ActiveOwnerValueInfo, new RecordItemIndex(43));
            //ActiveOwnerValue = repo.ApplicationUnderTest.ActiveOwnerValue.Element.GetAttributeValueText("Value");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "User", "$ActiveOwnerValue+$OtherPayAmnt", new RecordItemIndex(44));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TotalValue' at Center.", repo.ApplicationUnderTest.TotalValueInfo, new RecordItemIndex(45));
            repo.ApplicationUnderTest.TotalValue.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='$100,050') on item 'ApplicationUnderTest.TotalValue'.", repo.ApplicationUnderTest.TotalValueInfo, new RecordItemIndex(46));
            //Validate.AttributeEqual(repo.ApplicationUnderTest.TotalValueInfo, "Value", "$100,050");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnContinue' at Center.", repo.ApplicationUnderTest.BtnContinueInfo, new RecordItemIndex(47));
            repo.ApplicationUnderTest.BtnContinue.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
