///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Winston_Agent_Portal
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GAdditionalInsured recording.
    /// </summary>
    [TestModule("2fdcf850-2365-4266-92d6-a3e8bf434897", ModuleType.Recording, 1)]
    public partial class GAdditionalInsured : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Winston_Agent_PortalRepository repository.
        /// </summary>
        public static Winston_Agent_PortalRepository repo = Winston_Agent_PortalRepository.Instance;

        static GAdditionalInsured instance = new GAdditionalInsured();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GAdditionalInsured()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GAdditionalInsured Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'ApplicationUnderTest.fcg1002checkbox'.", repo.ApplicationUnderTest.fcg1002checkboxInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.ApplicationUnderTest.fcg1002checkboxInfo, "Checked", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Labelcheckbox' at Center.", repo.ApplicationUnderTest.LabelcheckboxInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Labelcheckbox.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Labelcheckbox1' at Center.", repo.ApplicationUnderTest.Labelcheckbox1Info, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Labelcheckbox1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Text' at Center.", repo.ApplicationUnderTest.TextInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Text.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.Text'.", repo.ApplicationUnderTest.TextInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Text.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.Text1' at Center.", repo.ApplicationUnderTest.Text1Info, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Text1.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest'.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.Self.EnsureVisible();
            Keyboard.Press("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Text1' at Center.", repo.ApplicationUnderTest.Text1Info, new RecordItemIndex(7));
            repo.ApplicationUnderTest.Text1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.Text1'.", repo.ApplicationUnderTest.Text1Info, new RecordItemIndex(8));
            repo.ApplicationUnderTest.Text1.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Text2' at Center.", repo.ApplicationUnderTest.Text2Info, new RecordItemIndex(9));
            repo.ApplicationUnderTest.Text2.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.Text2'.", repo.ApplicationUnderTest.Text2Info, new RecordItemIndex(10));
            repo.ApplicationUnderTest.Text2.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Text3' at Center.", repo.ApplicationUnderTest.Text3Info, new RecordItemIndex(11));
            repo.ApplicationUnderTest.Text3.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.Text3'.", repo.ApplicationUnderTest.Text3Info, new RecordItemIndex(12));
            repo.ApplicationUnderTest.Text3.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Text4' at Center.", repo.ApplicationUnderTest.Text4Info, new RecordItemIndex(13));
            repo.ApplicationUnderTest.Text4.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.Text4'.", repo.ApplicationUnderTest.Text4Info, new RecordItemIndex(14));
            repo.ApplicationUnderTest.Text4.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Text5' at Center.", repo.ApplicationUnderTest.Text5Info, new RecordItemIndex(15));
            repo.ApplicationUnderTest.Text5.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.Text5'.", repo.ApplicationUnderTest.Text5Info, new RecordItemIndex(16));
            repo.ApplicationUnderTest.Text5.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Text6' at Center.", repo.ApplicationUnderTest.Text6Info, new RecordItemIndex(17));
            repo.ApplicationUnderTest.Text6.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.Text6'.", repo.ApplicationUnderTest.Text6Info, new RecordItemIndex(18));
            repo.ApplicationUnderTest.Text6.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Text7' at Center.", repo.ApplicationUnderTest.Text7Info, new RecordItemIndex(19));
            repo.ApplicationUnderTest.Text7.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.Text7'.", repo.ApplicationUnderTest.Text7Info, new RecordItemIndex(20));
            repo.ApplicationUnderTest.Text7.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Text8' at Center.", repo.ApplicationUnderTest.Text8Info, new RecordItemIndex(21));
            repo.ApplicationUnderTest.Text8.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.Text8'.", repo.ApplicationUnderTest.Text8Info, new RecordItemIndex(22));
            repo.ApplicationUnderTest.Text8.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Text9' at Center.", repo.ApplicationUnderTest.Text9Info, new RecordItemIndex(23));
            repo.ApplicationUnderTest.Text9.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.Text9'.", repo.ApplicationUnderTest.Text9Info, new RecordItemIndex(24));
            repo.ApplicationUnderTest.Text9.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Text10' at Center.", repo.ApplicationUnderTest.Text10Info, new RecordItemIndex(25));
            repo.ApplicationUnderTest.Text10.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.Text10'.", repo.ApplicationUnderTest.Text10Info, new RecordItemIndex(26));
            repo.ApplicationUnderTest.Text10.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Labelcheckbox2' at Center.", repo.ApplicationUnderTest.Labelcheckbox2Info, new RecordItemIndex(27));
            repo.ApplicationUnderTest.Labelcheckbox2.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnSaveandContinue' at Center.", repo.ApplicationUnderTest.BtnSaveandContinueInfo, new RecordItemIndex(28));
            repo.ApplicationUnderTest.BtnSaveandContinue.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
