///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Winston_Agent_Portal
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GLQuote recording.
    /// </summary>
    [TestModule("b441bce3-98ae-4c2b-8d25-c7a0a98a8e32", ModuleType.Recording, 1)]
    public partial class GLQuote : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Winston_Agent_PortalRepository repository.
        /// </summary>
        public static Winston_Agent_PortalRepository repo = Winston_Agent_PortalRepository.Instance;

        static GLQuote instance = new GLQuote();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GLQuote()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GLQuote Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ExcessLiabilityOptions' at Center.", repo.ApplicationUnderTest.ExcessLiabilityOptionsInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.ExcessLiabilityOptions.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.GeneralLiabilityInsuranceCompany' at Center.", repo.ApplicationUnderTest.GeneralLiabilityInsuranceCompanyInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.GeneralLiabilityInsuranceCompany.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnSave2' at Center.", repo.ApplicationUnderTest.BtnSave2Info, new RecordItemIndex(2));
            repo.ApplicationUnderTest.BtnSave2.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CLOSE' at Center.", repo.ApplicationUnderTest.CLOSEInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.CLOSE.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(4));
            Delay.Duration(10000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
