///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Winston_Agent_Portal
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InlandMarine recording.
    /// </summary>
    [TestModule("96d4deca-fec1-4dd8-b1cd-ae1551bf0b28", ModuleType.Recording, 1)]
    public partial class InlandMarine : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Winston_Agent_PortalRepository repository.
        /// </summary>
        public static Winston_Agent_PortalRepository repo = Winston_Agent_PortalRepository.Instance;

        static InlandMarine instance = new InlandMarine();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InlandMarine()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InlandMarine Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LabelTagNo1' at Center.", repo.ApplicationUnderTest.LabelTagNo1Info, new RecordItemIndex(0));
            repo.ApplicationUnderTest.LabelTagNo1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LabelTagNo2' at Center.", repo.ApplicationUnderTest.LabelTagNo2Info, new RecordItemIndex(1));
            repo.ApplicationUnderTest.LabelTagNo2.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TblCoverages.NotCovered1' at Center.", repo.ApplicationUnderTest.TblCoverages.NotCovered1Info, new RecordItemIndex(2));
            repo.ApplicationUnderTest.TblCoverages.NotCovered1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '$10,000' with focus on 'ApplicationUnderTest'.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Self.EnsureVisible();
            Keyboard.Press("$10,000");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(4));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TblCoverages.NotCovered' at Center.", repo.ApplicationUnderTest.TblCoverages.NotCoveredInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.TblCoverages.NotCovered.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '$5,000' with focus on 'ApplicationUnderTest'.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.Self.EnsureVisible();
            Keyboard.Press("$5,000");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(7));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TblCoverages.NotCovered2' at Center.", repo.ApplicationUnderTest.TblCoverages.NotCovered2Info, new RecordItemIndex(8));
            repo.ApplicationUnderTest.TblCoverages.NotCovered2.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '$10,000' with focus on 'ApplicationUnderTest'.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.Self.EnsureVisible();
            Keyboard.Press("$10,000");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(10));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnAdd' at Center.", repo.ApplicationUnderTest.BtnAddInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.BtnAdd.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtType' at Center.", repo.ApplicationUnderTest.TxtTypeInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.TxtType.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Car' with focus on 'ApplicationUnderTest.TxtType'.", repo.ApplicationUnderTest.TxtTypeInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.TxtType.PressKeys("Car");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtACVLimit' at Center.", repo.ApplicationUnderTest.TxtACVLimitInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.TxtACVLimit.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '10000' with focus on 'ApplicationUnderTest.TxtACVLimit'.", repo.ApplicationUnderTest.TxtACVLimitInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.TxtACVLimit.PressKeys("10000");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnSave1' at Center.", repo.ApplicationUnderTest.BtnSave1Info, new RecordItemIndex(16));
            repo.ApplicationUnderTest.BtnSave1.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
