///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Winston_Agent_Portal
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("4b2b5806-8a2c-4b87-80b3-9d1ae3343323", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Winston_Agent_PortalRepository repository.
        /// </summary>
        public static Winston_Agent_PortalRepository repo = Winston_Agent_PortalRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
            UserName = "Acentria36";
            Password = "AI495!";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

        string _UserName;

        /// <summary>
        /// Gets or sets the value of variable UserName.
        /// </summary>
        [TestVariable("20599425-e60c-4195-a8d2-809e2794351c")]
        public string UserName
        {
            get { return _UserName; }
            set { _UserName = value; }
        }

        string _Password;

        /// <summary>
        /// Gets or sets the value of variable Password.
        /// </summary>
        [TestVariable("c038f557-472c-4119-964e-7fe35c4cc745")]
        public string Password
        {
            get { return _Password; }
            set { _Password = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable AgencyName.
        /// </summary>
        [TestVariable("077dd62f-01bc-453b-9b30-9275e4326288")]
        public string AgencyName
        {
            get { return repo.AgencyName; }
            set { repo.AgencyName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Header text
            Report.Log(ReportLevel.Info, "Section", "Header text", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsDevWinstonFwcinsComFWCPortal.TxtBranchId' at 27;15.", repo.HttpsDevWinstonFwcinsComFWCPortal.TxtBranchIdInfo, new RecordItemIndex(1));
            repo.HttpsDevWinstonFwcinsComFWCPortal.TxtBranchId.Click("27;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$UserName' on item 'HttpsDevWinstonFwcinsComFWCPortal.TxtBranchId'.", repo.HttpsDevWinstonFwcinsComFWCPortal.TxtBranchIdInfo, new RecordItemIndex(2));
            repo.HttpsDevWinstonFwcinsComFWCPortal.TxtBranchId.Element.SetAttributeValue("Value", UserName);
            Delay.Milliseconds(0);
            
            // Password
            Report.Log(ReportLevel.Info, "Section", "Password", new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsDevWinstonFwcinsComFWCPortal.TxtPassword' at 48;13.", repo.HttpsDevWinstonFwcinsComFWCPortal.TxtPasswordInfo, new RecordItemIndex(4));
            repo.HttpsDevWinstonFwcinsComFWCPortal.TxtPassword.Click("48;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$Password' on item 'HttpsDevWinstonFwcinsComFWCPortal.TxtPassword'.", repo.HttpsDevWinstonFwcinsComFWCPortal.TxtPasswordInfo, new RecordItemIndex(5));
            repo.HttpsDevWinstonFwcinsComFWCPortal.TxtPassword.Element.SetAttributeValue("Value", Password);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsDevWinstonFwcinsComFWCPortal.SignIn' at 60;13.", repo.HttpsDevWinstonFwcinsComFWCPortal.SignInInfo, new RecordItemIndex(6));
            repo.HttpsDevWinstonFwcinsComFWCPortal.SignIn.Click("60;13");
            Delay.Milliseconds(0);
            
            // Agency selection
            Report.Log(ReportLevel.Info, "Section", "Agency selection", new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsDevWinstonFwcinsComFWCPortal.SomeBTag' at 4;3.", repo.HttpsDevWinstonFwcinsComFWCPortal.SomeBTagInfo, new RecordItemIndex(8));
            repo.HttpsDevWinstonFwcinsComFWCPortal.SomeBTag.Click("4;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsDevWinstonFwcinsComFWCPortal.AgencyName' at 46;17.", repo.HttpsDevWinstonFwcinsComFWCPortal.AgencyNameInfo, new RecordItemIndex(9));
            repo.HttpsDevWinstonFwcinsComFWCPortal.AgencyName.Click("46;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsDevWinstonFwcinsComFWCPortal.BtnContinue' at 48;13.", repo.HttpsDevWinstonFwcinsComFWCPortal.BtnContinueInfo, new RecordItemIndex(10));
            repo.HttpsDevWinstonFwcinsComFWCPortal.BtnContinue.Click("48;13");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
