///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Winston_Agent_Portal
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NQ_GL recording.
    /// </summary>
    [TestModule("88ebd9d3-571d-4a2a-982d-38eb9c2eea70", ModuleType.Recording, 1)]
    public partial class NQ_GL : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Winston_Agent_PortalRepository repository.
        /// </summary>
        public static Winston_Agent_PortalRepository repo = Winston_Agent_PortalRepository.Instance;

        static NQ_GL instance = new NQ_GL();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NQ_GL()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NQ_GL Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LnkNewQuote' at Center.", repo.ApplicationUnderTest.LnkNewQuoteInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.LnkNewQuote.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'ApplicationUnderTest.GeneralLiability'", repo.ApplicationUnderTest.GeneralLiabilityInfo, new ActionTimeout(10000), new RecordItemIndex(1));
            repo.ApplicationUnderTest.GeneralLiabilityInfo.WaitForExists(10000);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HideThisMessage' at Center.", repo.ApplicationUnderTest.HideThisMessageInfo, new RecordItemIndex(2));
            //repo.ApplicationUnderTest.HideThisMessage.Click();
            //Delay.Milliseconds(0);
            
            Mouse_Click_GeneralLiability(repo.ApplicationUnderTest.GeneralLiabilityInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnSave' at Center.", repo.ApplicationUnderTest.BtnSaveInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.BtnSave.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
