///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Winston_Agent_Portal
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Winston_Agent_PortalRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("7f2a20b6-644f-4206-825f-8ef87802e496")]
    public partial class Winston_Agent_PortalRepository : RepoGenBaseFolder
    {
        static Winston_Agent_PortalRepository instance = new Winston_Agent_PortalRepository();
        Winston_Agent_PortalRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        Winston_Agent_PortalRepositoryFolders.HttpsDevWinstonFwcinsComFWCPortalAppFolder _httpsdevwinstonfwcinscomfwcportal;

        /// <summary>
        /// Gets the singleton class instance representing the Winston_Agent_PortalRepository element repository.
        /// </summary>
        [RepositoryFolder("7f2a20b6-644f-4206-825f-8ef87802e496")]
        public static Winston_Agent_PortalRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Winston_Agent_PortalRepository() 
            : base("Winston_Agent_PortalRepository", "/", null, 0, false, "7f2a20b6-644f-4206-825f-8ef87802e496", ".\\RepositoryImages\\Winston_Agent_PortalRepository7f2a20b6.rximgres")
        {
            _applicationundertest = new Winston_Agent_PortalRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _httpsdevwinstonfwcinscomfwcportal = new Winston_Agent_PortalRepositoryFolders.HttpsDevWinstonFwcinsComFWCPortalAppFolder(this);
        }

#region Variables

        string _AgencyName = "Christina Bowman";

        /// <summary>
        /// Gets or sets the value of variable AgencyName.
        /// </summary>
        [TestVariable("077dd62f-01bc-453b-9b30-9275e4326288")]
        public string AgencyName
        {
            get { return _AgencyName; }
            set { _AgencyName = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7f2a20b6-644f-4206-825f-8ef87802e496")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("ee96e4cd-5a4c-4be2-828f-6b678101c20f")]
        public virtual Winston_Agent_PortalRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The HttpsDevWinstonFwcinsComFWCPortal folder.
        /// </summary>
        [RepositoryFolder("60526d6e-c662-4ed1-b53c-ba575967ab29")]
        public virtual Winston_Agent_PortalRepositoryFolders.HttpsDevWinstonFwcinsComFWCPortalAppFolder HttpsDevWinstonFwcinsComFWCPortal
        {
            get { return _httpsdevwinstonfwcinscomfwcportal; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Winston_Agent_PortalRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("ee96e4cd-5a4c-4be2-828f-6b678101c20f")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lnknewquoteInfo;
            RepoItemInfo _hidethismessageInfo;
            RepoItemInfo _generalliabilityInfo;
            RepoItemInfo _btnsaveInfo;
            RepoItemInfo _select2ddlagencycontactcontainerInfo;
            RepoItemInfo _waitInfo;
            RepoItemInfo _somedivtagInfo;
            RepoItemInfo _colmdInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='dev_winston.fwcins.com']", parentFolder, 30000, null, false, "ee96e4cd-5a4c-4be2-828f-6b678101c20f", "")
            {
                _lnknewquoteInfo = new RepoItemInfo(this, "LnkNewQuote", ".//a[#'lnkNewQuote']", 30000, null, "250a74c8-deba-4833-a3fb-61ac0b8bfa69");
                _hidethismessageInfo = new RepoItemInfo(this, "HideThisMessage", "body/div[7]/?/?/iframe[@src='about:blank']/body//tag[@tagname='cue']/div/?/?/a[@innertext='Hide this message']", 30000, null, "317786c5-ae48-43b8-9580-dc3c5da6bae9");
                _generalliabilityInfo = new RepoItemInfo(this, "GeneralLiability", "body/div[3]/div[4]/div[2]/div/div[2]/?/?/label[@innertext='General Liability']", 30000, null, "fe8fd9b1-a9dc-4a29-b77e-75ce5d582454");
                _btnsaveInfo = new RepoItemInfo(this, "BtnSave", ".//button[#'BtnSave']", 30000, null, "978f3d25-9361-44df-ae50-9c8ce7a211b2");
                _select2ddlagencycontactcontainerInfo = new RepoItemInfo(this, "Select2DdlAgencyContactContainer", ".//span[#'select2-ddlAgencyContact-container']", 30000, null, "2927f3ac-5772-4396-bb8f-2e702056eb7c");
                _waitInfo = new RepoItemInfo(this, "Wait", ".//div[#'wait']", 30000, null, "1ccd8c12-29cb-435f-a39f-68bef1b2a24f");
                _somedivtagInfo = new RepoItemInfo(this, "SomeDivTag", "body/div[2]", 30000, null, "5f26b9b3-758e-4809-bb8d-2ee9535b3ca0");
                _colmdInfo = new RepoItemInfo(this, "ColMd", ".//form[#'frmLogin']/div/div/div/div[2]/div[3]", 30000, null, "d6dc7dc3-232f-4e4d-8f69-88e09b20d96c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ee96e4cd-5a4c-4be2-828f-6b678101c20f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ee96e4cd-5a4c-4be2-828f-6b678101c20f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LnkNewQuote item.
            /// </summary>
            [RepositoryItem("250a74c8-deba-4833-a3fb-61ac0b8bfa69")]
            public virtual Ranorex.ATag LnkNewQuote
            {
                get
                {
                    return _lnknewquoteInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LnkNewQuote item info.
            /// </summary>
            [RepositoryItemInfo("250a74c8-deba-4833-a3fb-61ac0b8bfa69")]
            public virtual RepoItemInfo LnkNewQuoteInfo
            {
                get
                {
                    return _lnknewquoteInfo;
                }
            }

            /// <summary>
            /// The HideThisMessage item.
            /// </summary>
            [RepositoryItem("317786c5-ae48-43b8-9580-dc3c5da6bae9")]
            public virtual Ranorex.ATag HideThisMessage
            {
                get
                {
                    return _hidethismessageInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HideThisMessage item info.
            /// </summary>
            [RepositoryItemInfo("317786c5-ae48-43b8-9580-dc3c5da6bae9")]
            public virtual RepoItemInfo HideThisMessageInfo
            {
                get
                {
                    return _hidethismessageInfo;
                }
            }

            /// <summary>
            /// The GeneralLiability item.
            /// </summary>
            [RepositoryItem("fe8fd9b1-a9dc-4a29-b77e-75ce5d582454")]
            public virtual Ranorex.LabelTag GeneralLiability
            {
                get
                {
                    return _generalliabilityInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The GeneralLiability item info.
            /// </summary>
            [RepositoryItemInfo("fe8fd9b1-a9dc-4a29-b77e-75ce5d582454")]
            public virtual RepoItemInfo GeneralLiabilityInfo
            {
                get
                {
                    return _generalliabilityInfo;
                }
            }

            /// <summary>
            /// The BtnSave item.
            /// </summary>
            [RepositoryItem("978f3d25-9361-44df-ae50-9c8ce7a211b2")]
            public virtual Ranorex.ButtonTag BtnSave
            {
                get
                {
                    return _btnsaveInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnSave item info.
            /// </summary>
            [RepositoryItemInfo("978f3d25-9361-44df-ae50-9c8ce7a211b2")]
            public virtual RepoItemInfo BtnSaveInfo
            {
                get
                {
                    return _btnsaveInfo;
                }
            }

            /// <summary>
            /// The Select2DdlAgencyContactContainer item.
            /// </summary>
            [RepositoryItem("2927f3ac-5772-4396-bb8f-2e702056eb7c")]
            public virtual Ranorex.SpanTag Select2DdlAgencyContactContainer
            {
                get
                {
                    return _select2ddlagencycontactcontainerInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Select2DdlAgencyContactContainer item info.
            /// </summary>
            [RepositoryItemInfo("2927f3ac-5772-4396-bb8f-2e702056eb7c")]
            public virtual RepoItemInfo Select2DdlAgencyContactContainerInfo
            {
                get
                {
                    return _select2ddlagencycontactcontainerInfo;
                }
            }

            /// <summary>
            /// The Wait item.
            /// </summary>
            [RepositoryItem("1ccd8c12-29cb-435f-a39f-68bef1b2a24f")]
            public virtual Ranorex.DivTag Wait
            {
                get
                {
                    return _waitInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Wait item info.
            /// </summary>
            [RepositoryItemInfo("1ccd8c12-29cb-435f-a39f-68bef1b2a24f")]
            public virtual RepoItemInfo WaitInfo
            {
                get
                {
                    return _waitInfo;
                }
            }

            /// <summary>
            /// The SomeDivTag item.
            /// </summary>
            [RepositoryItem("5f26b9b3-758e-4809-bb8d-2ee9535b3ca0")]
            public virtual Ranorex.DivTag SomeDivTag
            {
                get
                {
                    return _somedivtagInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SomeDivTag item info.
            /// </summary>
            [RepositoryItemInfo("5f26b9b3-758e-4809-bb8d-2ee9535b3ca0")]
            public virtual RepoItemInfo SomeDivTagInfo
            {
                get
                {
                    return _somedivtagInfo;
                }
            }

            /// <summary>
            /// The ColMd item.
            /// </summary>
            [RepositoryItem("d6dc7dc3-232f-4e4d-8f69-88e09b20d96c")]
            public virtual Ranorex.DivTag ColMd
            {
                get
                {
                    return _colmdInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ColMd item info.
            /// </summary>
            [RepositoryItemInfo("d6dc7dc3-232f-4e4d-8f69-88e09b20d96c")]
            public virtual RepoItemInfo ColMdInfo
            {
                get
                {
                    return _colmdInfo;
                }
            }
        }

        /// <summary>
        /// The HttpsDevWinstonFwcinsComFWCPortalAppFolder folder.
        /// </summary>
        [RepositoryFolder("60526d6e-c662-4ed1-b53c-ba575967ab29")]
        public partial class HttpsDevWinstonFwcinsComFWCPortalAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtbranchidInfo;
            RepoItemInfo _txtpasswordInfo;
            RepoItemInfo _signinInfo;
            RepoItemInfo _somebtagInfo;
            RepoItemInfo _agencynameInfo;
            RepoItemInfo _btncontinueInfo;

            /// <summary>
            /// Creates a new HttpsDevWinstonFwcinsComFWCPortal  folder.
            /// </summary>
            public HttpsDevWinstonFwcinsComFWCPortalAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpsDevWinstonFwcinsComFWCPortal", "/dom[@domain='dev_winston.fwcins.com']", parentFolder, 30000, null, false, "60526d6e-c662-4ed1-b53c-ba575967ab29", "")
            {
                _txtbranchidInfo = new RepoItemInfo(this, "TxtBranchId", ".//input[#'txtBranchId']", 30000, null, "603579aa-6208-46fa-93f0-40ef83876138");
                _txtpasswordInfo = new RepoItemInfo(this, "TxtPassword", ".//input[#'txtPassword']", 30000, null, "a2b09389-5c49-49e3-af85-718e44d4020a");
                _signinInfo = new RepoItemInfo(this, "SignIn", ".//form[#'frmLogin']/div/div/div/div[2]/div[2]/div[4]/button[@innertext='Sign in']", 30000, null, "be8727b1-1d9b-486f-9e17-4661ba84ba46");
                _somebtagInfo = new RepoItemInfo(this, "SomeBTag", ".//form[#'frmSelectAgency']/div/div[1]/div/div[2]/div/span/span[1]//b", 30000, null, "0b13023d-75df-4681-9c74-7db54b04541c");
                _agencynameInfo = new RepoItemInfo(this, "AgencyName", ".//ul[#'select2-ddlAgencyContact-results']/li[@innertext=$AgencyName]", 30000, null, "ada8c2df-ff5a-4f10-b71b-9f110598e45a");
                _btncontinueInfo = new RepoItemInfo(this, "BtnContinue", ".//button[#'btnContinue']", 30000, null, "aff91744-5dcc-4875-9fd5-d57ec5865c90");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("60526d6e-c662-4ed1-b53c-ba575967ab29")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("60526d6e-c662-4ed1-b53c-ba575967ab29")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtBranchId item.
            /// </summary>
            [RepositoryItem("603579aa-6208-46fa-93f0-40ef83876138")]
            public virtual Ranorex.InputTag TxtBranchId
            {
                get
                {
                    return _txtbranchidInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtBranchId item info.
            /// </summary>
            [RepositoryItemInfo("603579aa-6208-46fa-93f0-40ef83876138")]
            public virtual RepoItemInfo TxtBranchIdInfo
            {
                get
                {
                    return _txtbranchidInfo;
                }
            }

            /// <summary>
            /// The TxtPassword item.
            /// </summary>
            [RepositoryItem("a2b09389-5c49-49e3-af85-718e44d4020a")]
            public virtual Ranorex.InputTag TxtPassword
            {
                get
                {
                    return _txtpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtPassword item info.
            /// </summary>
            [RepositoryItemInfo("a2b09389-5c49-49e3-af85-718e44d4020a")]
            public virtual RepoItemInfo TxtPasswordInfo
            {
                get
                {
                    return _txtpasswordInfo;
                }
            }

            /// <summary>
            /// The SignIn item.
            /// </summary>
            [RepositoryItem("be8727b1-1d9b-486f-9e17-4661ba84ba46")]
            public virtual Ranorex.ButtonTag SignIn
            {
                get
                {
                    return _signinInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SignIn item info.
            /// </summary>
            [RepositoryItemInfo("be8727b1-1d9b-486f-9e17-4661ba84ba46")]
            public virtual RepoItemInfo SignInInfo
            {
                get
                {
                    return _signinInfo;
                }
            }

            /// <summary>
            /// The SomeBTag item.
            /// </summary>
            [RepositoryItem("0b13023d-75df-4681-9c74-7db54b04541c")]
            public virtual Ranorex.BTag SomeBTag
            {
                get
                {
                    return _somebtagInfo.CreateAdapter<Ranorex.BTag>(true);
                }
            }

            /// <summary>
            /// The SomeBTag item info.
            /// </summary>
            [RepositoryItemInfo("0b13023d-75df-4681-9c74-7db54b04541c")]
            public virtual RepoItemInfo SomeBTagInfo
            {
                get
                {
                    return _somebtagInfo;
                }
            }

            /// <summary>
            /// The AgencyName item.
            /// </summary>
            [RepositoryItem("ada8c2df-ff5a-4f10-b71b-9f110598e45a")]
            public virtual Ranorex.LiTag AgencyName
            {
                get
                {
                    return _agencynameInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The AgencyName item info.
            /// </summary>
            [RepositoryItemInfo("ada8c2df-ff5a-4f10-b71b-9f110598e45a")]
            public virtual RepoItemInfo AgencyNameInfo
            {
                get
                {
                    return _agencynameInfo;
                }
            }

            /// <summary>
            /// The BtnContinue item.
            /// </summary>
            [RepositoryItem("aff91744-5dcc-4875-9fd5-d57ec5865c90")]
            public virtual Ranorex.ButtonTag BtnContinue
            {
                get
                {
                    return _btncontinueInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnContinue item info.
            /// </summary>
            [RepositoryItemInfo("aff91744-5dcc-4875-9fd5-d57ec5865c90")]
            public virtual RepoItemInfo BtnContinueInfo
            {
                get
                {
                    return _btncontinueInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
